import type { WorkItem } from "../types";

/**
 * 작업 항목 레지스트리 — 코어스 EPIC DAG (비순환 보장).
 * 제1원칙(SoT 이중화 금지): 세부 작업은 tasks/*.md ↔ GitHub 이슈가 단일 SoT다.
 * 여기 EPIC 은 그 위의 마일스톤 레이어이며, externalRefs 로 task 패밀리를 **교차참조**한다(복제 아님).
 * "모든 tasks/*.md 가 정확히 1개 EPIC 에 매핑"은 무결성 테스트(task-coverage)로 강제한다.
 * dependsOn = 선행 id, screens = 건드리는 화면 키(`plane/slug`).
 */
export const WORK_ITEMS: WorkItem[] = [
  {
    id: "W01",
    title: "디자인 시스템 토큰(VDS)",
    phase: "P0 디자인·프로토타입",
    status: "done",
    externalRefs: "UI_* (디자인 토큰), IF-FONT-001",
    dependsOn: [],
    screens: [],
    doc: "app/globals.css",
  },
  {
    id: "W02",
    title: "랜딩 페이지 구현",
    phase: "P0 디자인·프로토타입",
    status: "done",
    externalRefs: "UI_* (landing), FW-NL-001, FR-EXP-*",
    dependsOn: ["W01"],
    screens: ["learner/landing"],
    doc: "docs/PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W03",
    title: "레슨 플레이어·OX 퀴즈",
    phase: "P0 디자인·프로토타입",
    status: "done",
    externalRefs: "FR-LES-*, FW-OX-*, FW-PROG-*, UI_FR-LES-*, CT-DB-006, TS-UT-003/004",
    dependsOn: ["W01"],
    screens: ["learner/lesson"],
    doc: "docs/PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W04",
    title: "용어 사전",
    phase: "P0 디자인·프로토타입",
    status: "done",
    externalRefs: "FR-DICT-001, FR-LINT-001, UI_* (dictionary)",
    dependsOn: ["W01"],
    screens: ["learner/dictionary"],
    doc: "docs/PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W05",
    title: "스탬프 맵 UI",
    phase: "P0 디자인·프로토타입",
    status: "done",
    externalRefs: "FR-STAMP-*, UI_FR-STAMP-*",
    dependsOn: ["W01"],
    screens: ["learner/stamp-map"],
    doc: "docs/PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W06",
    title: "로그인·회원가입 UI",
    phase: "P0 디자인·프로토타입",
    status: "done",
    externalRefs: "UI_FR-AUTH-*, FR-AUTH-*",
    dependsOn: ["W01"],
    screens: ["learner/auth"],
    doc: "docs/PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W07",
    title: "교사용 자료 화면",
    phase: "P0 디자인·프로토타입",
    status: "done",
    externalRefs: "FR-TF-001, FR-PDF-*, UI_* (teacher-kit)",
    dependsOn: ["W01"],
    screens: ["operator/teacher-kit"],
    doc: "docs/PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W08",
    title: "관리자 대시보드 UI",
    phase: "P0 디자인·프로토타입",
    status: "done",
    externalRefs: "FR-KPI-*, UI_* (admin)",
    dependsOn: ["W01"],
    screens: ["operator/admin-dashboard"],
    doc: "docs/PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W09",
    title: "404·시스템 상태",
    phase: "P0 디자인·프로토타입",
    status: "done",
    externalRefs: "UI_* (empty-states)",
    dependsOn: ["W01"],
    screens: ["system/not-found"],
    doc: "docs/PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W10",
    title: "인증 백엔드(Kakao OAuth)",
    phase: "P1 백엔드·영속화",
    status: "todo",
    externalRefs: "FW-AUTH-001..006, CT-DB-002, CT-DB-011, IF-SUP-001, TS-UT-001/002",
    dependsOn: ["W06"],
    screens: ["learner/auth", "operator/admin-dashboard"],
    doc: "tasks/FW-AUTH-006_Infra_Auth_Kakao_OAuth.md",
  },
  {
    id: "W11",
    title: "학습 진척 영속화",
    phase: "P1 백엔드·영속화",
    status: "todo",
    externalRefs: "FW-PROG-*, FW-OX-*, FW-STAMP-001, CT-DB-004/005, TS-UT-005/006/007, TS-IT-001",
    dependsOn: ["W10", "W03", "W05"],
    screens: ["learner/lesson", "learner/stamp-map"],
    doc: "tasks/CT-DB-004_Schema_LessonProgress_Model.md",
  },
  {
    id: "W12",
    title: "관리자 인증·역할 게이트",
    phase: "P1 백엔드·영속화",
    status: "todo",
    externalRefs: "TS-UT-013, FW-AUTH-005, CT-DB-011",
    dependsOn: ["W10"],
    screens: ["operator/admin-dashboard"],
    doc: "tasks/TS-UT-013_Test_Unit_RBAC_Guard_Learner_403.md",
  },
  {
    id: "W13",
    title: "PDF 다운로드 백엔드",
    phase: "P1 백엔드·영속화",
    status: "todo",
    externalRefs: "FW-PDF-*, FW-TF-*, CT-DB-007, IF-CACHE-*, TS-IT-004/005/006",
    dependsOn: ["W07"],
    screens: ["operator/teacher-kit"],
    doc: "tasks/CT-DB-007_Schema_TeacherFeedback_TeacherKit.md",
  },
  {
    id: "W14",
    title: "콘텐츠 CMS 연동",
    phase: "P1 백엔드·영속화",
    status: "todo",
    externalRefs: "CT-DB-003, CT-DB-010, IF-SCALE-*, FR-LES-002",
    dependsOn: ["W08"],
    screens: ["operator/admin-dashboard"],
    doc: "tasks/CT-DB-003_Schema_Lesson_3Media_NotNull.md",
  },
  {
    id: "W15",
    title: "접근성 감사·보강",
    phase: "P2 품질·운영",
    status: "todo",
    externalRefs: "TS-E2E-003..006, IF-CI-002, IF-FONT-001",
    dependsOn: ["W02", "W03"],
    screens: ["learner/landing", "learner/lesson"],
    doc: "tasks/IF-CI-002_Infra_CI_Axe_Lighthouse_Alpha_Gate.md",
  },
  {
    id: "W16",
    title: "관측성·계측 도입",
    phase: "P2 품질·운영",
    status: "todo",
    externalRefs: "NF-OBS-*, CT-DB-009, IF-AN-001, FR-KPI-*, TS-IT-002",
    dependsOn: ["W10"],
    screens: ["learner/landing", "learner/lesson", "operator/teacher-kit"],
    doc: "tasks/NF-OBS-001_NF_Sentry_Setup_Sampling.md",
  },
];

export const getWorkItem = (id: string): WorkItem | undefined =>
  WORK_ITEMS.find((w) => w.id === id);
